# Installs idarem so IDA auto-loads it on every start, and builds the web UI.
#
# It does NOT copy the plugin into IDA. Instead it drops a tiny loader into IDA's
# user plugins folder that executes the real plugin straight from this repo. So
# you edit/rebuild in place — no dragging files around, no re-installing.
#
#   Usage:  powershell -ExecutionPolicy Bypass -File scripts\install.ps1

$ErrorActionPreference = "Stop"

# IDA's per-user dir is independent of where IDA.exe is installed (any folder or
# drive). It's $IDAUSR if set (may be a ;-separated list — take the first), else
# %APPDATA%\Hex-Rays\IDA Pro. Plugins dropped here load for every IDA install.
function Get-IdaUserDir {
    if ($env:IDAUSR) { return ($env:IDAUSR -split ';')[0] }
    return (Join-Path $env:APPDATA "Hex-Rays\IDA Pro")
}

$RepoRoot   = Split-Path -Parent $PSScriptRoot
$PluginFile = Join-Path $RepoRoot "plugin\idarem.py"
$WebDir     = Join-Path $RepoRoot "web"

if (-not (Test-Path $PluginFile)) { throw "Plugin not found at $PluginFile" }

# 1. Build the web client (so the plugin can serve it).
Write-Host "[1/3] Building the web client..." -ForegroundColor Cyan
Push-Location $WebDir
try {
    if (-not (Test-Path "node_modules")) { npm install }
    npm run build
}
finally { Pop-Location }

# 2. Locate IDA's per-user plugins folder (auto-loaded on every start).
$PluginsDir = Join-Path (Get-IdaUserDir) "plugins"
New-Item -ItemType Directory -Force -Path $PluginsDir | Out-Null

# 3. Write the loader. It execs the repo plugin by absolute path, so __file__
#    points back here and the plugin's web-root auto-detection still works.
$Loader = @"
# Auto-generated by idarem scripts/install.ps1 -- do not edit.
# Loads the real plugin from the repo so edits/rebuilds need no re-install.
import importlib.util
import traceback

_REAL = r"$PluginFile"

try:
    _spec = importlib.util.spec_from_file_location("idarem_impl", _REAL)
    _mod = importlib.util.module_from_spec(_spec)
    _spec.loader.exec_module(_mod)

    def PLUGIN_ENTRY():
        return _mod.PLUGIN_ENTRY()

except Exception:
    # Surface the real reason in IDA's Output window instead of failing silently.
    print("[idarem] FAILED to load plugin from:", _REAL)
    traceback.print_exc()
    raise
"@
$LoaderPath = Join-Path $PluginsDir "idarem.py"
# UTF-8 WITHOUT a BOM: PowerShell 5.1's -Encoding UTF8 prepends a BOM (U+FEFF),
# which IDA's Python compiler rejects as a non-printable character on line 1.
$Utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($LoaderPath, $Loader, $Utf8NoBom)

Write-Host "[2/3] Installed loader -> $LoaderPath" -ForegroundColor Cyan
Write-Host "[3/3] Done." -ForegroundColor Green
Write-Host ""
Write-Host "Restart IDA. The plugin loads automatically (Ctrl-Alt-R toggles it)" -ForegroundColor Yellow
Write-Host "and serves the UI at http://localhost:8765." -ForegroundColor Yellow
Write-Host "Delete any older ida_remote.py / hand-copied plugin in IDA's plugins folder." -ForegroundColor Yellow
